### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by occuros** [reneeichhorn/bevy-remote-devtools#4]
When I add the dependency to the bevy applications, the compilation fails with a linker error (on both Windows 10 and MacOS):

```
error: linking with `rust-lld.exe` failed: exit code: 1

  = note: rust-lld: error: undefined symbol: _$LT$hyper..body..body..Body$u20$as$u20$http_body..Body$GT$::poll_data::hc4c5b739c6fca22c
```

This happens even without using the `dynamic` feature of rust.

Any help would be appreciated.

**Comment by reneeichhorn** [comment]
Have you tried adding the patch for hyper?
```toml
[patch.crates-io]
hyper = { git = "https://github.com/reneeichhorn/hyper.git" }
```
